# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bla/my_projects/otpam

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bla/my_projects/otpam

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bla/my_projects/otpam/CMakeFiles /home/bla/my_projects/otpam/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bla/my_projects/otpam/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pppv3

# Build rule for target.
pppv3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pppv3
.PHONY : pppv3

# fast build rule for target.
pppv3/fast:
	$(MAKE) -f CMakeFiles/pppv3.dir/build.make CMakeFiles/pppv3.dir/build
.PHONY : pppv3/fast

# target to build an object file
crypto.o:
	$(MAKE) -f CMakeFiles/pppv3.dir/build.make CMakeFiles/pppv3.dir/crypto.o
.PHONY : crypto.o

# target to preprocess a source file
crypto.i:
	$(MAKE) -f CMakeFiles/pppv3.dir/build.make CMakeFiles/pppv3.dir/crypto.i
.PHONY : crypto.i

# target to generate assembly for a file
crypto.s:
	$(MAKE) -f CMakeFiles/pppv3.dir/build.make CMakeFiles/pppv3.dir/crypto.s
.PHONY : crypto.s

# target to build an object file
num.o:
	$(MAKE) -f CMakeFiles/pppv3.dir/build.make CMakeFiles/pppv3.dir/num.o
.PHONY : num.o

# target to preprocess a source file
num.i:
	$(MAKE) -f CMakeFiles/pppv3.dir/build.make CMakeFiles/pppv3.dir/num.i
.PHONY : num.i

# target to generate assembly for a file
num.s:
	$(MAKE) -f CMakeFiles/pppv3.dir/build.make CMakeFiles/pppv3.dir/num.s
.PHONY : num.s

# target to build an object file
pppv3.o:
	$(MAKE) -f CMakeFiles/pppv3.dir/build.make CMakeFiles/pppv3.dir/pppv3.o
.PHONY : pppv3.o

# target to preprocess a source file
pppv3.i:
	$(MAKE) -f CMakeFiles/pppv3.dir/build.make CMakeFiles/pppv3.dir/pppv3.i
.PHONY : pppv3.i

# target to generate assembly for a file
pppv3.s:
	$(MAKE) -f CMakeFiles/pppv3.dir/build.make CMakeFiles/pppv3.dir/pppv3.s
.PHONY : pppv3.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... pppv3"
	@echo "... rebuild_cache"
	@echo "... crypto.o"
	@echo "... crypto.i"
	@echo "... crypto.s"
	@echo "... num.o"
	@echo "... num.i"
	@echo "... num.s"
	@echo "... pppv3.o"
	@echo "... pppv3.i"
	@echo "... pppv3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

