.\"
.\"   otpasswd(1) - One-time password management utility man page
.\"
.\"   Copyright (c) 2010 Tomasz bla Fortuna
.\"
.\"   Permission is granted to copy, distribute and/or modify this document
.\"   under the terms of the GNU Free Documentation License, Version 1.3
.\"   or any later version published by the Free Software Foundation;
.\"   with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\"   A copy of the license is included in the main directory of the OTPasswd
.\"   source package in the LICENSE.FDL file.
.\"
.\"   Author:  R Hannes Beinert & Tomasz bla Fortuna
.\"   Version: otpasswd v0.5pre1
.\"   Update:  02-Jan-10
.\"

.TH OTPASSWD 1 2010-01-02 GNU "OTPasswd User Manual"

.SH NAME
otpasswd \- One-time password management utility

.SH SYNOPSIS
.B otpasswd
[\fIoptions\fR]

.SH DESCRIPTION
The \fIotpasswd\fR utility serves as the primary management tool
for the \fBOTPasswd\fR one-time password authentication package
for both users and administrators.
It allows the user to generate a key, print passcards,
and manage various configuration options.

.SH OPTIONS
.SS Key Generation
.TP
\fB\-k\fR, \fB\-\-key\fR
Generate a new key.
Can be combined with -f, -d and -c. If user already has state,
OTPasswd can either, use default flag set and then modify it 
by user options, or use previous state as defaults. User will
be asked what he prefers.

After state is prepared, OTPasswd prints first passcard and waits until 
user manages to note/print them down.

.TP
\fB\-r\fR, \fB\-\-remove\fR
Remove user state.

.SS Passcard Printing
.TP
\fB\-t\fR, \fB\-\-text\fR ( \fIcard\fR | \fIcode\fR )
Generate either one ASCII passcard, or a single passcode.

.TP
\fB\-l\fR, \fB\-\-latex\fR ( \fIcard\fR | \fIcode\fR )
Generate six (6) LaTeX passcards beginning with the specified passcard.

.SS Miscellaneous Passcode Operations
.TP
\fB\-P\fR, \fB\-\-prompt\fR ( \fIcard\fR | \fIcode\fR )
Display authentication prompt for the specified passcode.

.TP
\fB\-a\fR, \fB\-\-authenticate\fR \fIpasscode\fR
Attempt authentication with the actual passcode specified.
This might be used for testing or scripted authentication.

.TP
\fB\-s\fR, \fB\-\-skip\fR ( \fIcard\fR | \fIcode\fR )
Skip forward to a specific point in the passcode sequence.
The next authentication request will request either the specified passcode,
or the first passcode on the specified passcard.

.TP
\fB\-w\fR, \fB\-\-warning\fR
Display any current warnings.
For example, if the user is currently on the last printed passcard.

.SS Configuration
.TP
\fB\-f\fR, \fB\-\-flag\fR \fIflag\fR
Set various flags which regulate \fBOTPasswd\fR system behavior:
.RS
.RS +4m
.PD 0
.TP +19m
\fBshow\fR
Show passcode when authenticating. (default)
.TP +19m
\fBdont\-show\fR
Do not show passcode when authenticating.

.TP +19m
\fBalphabet\-\fIX\fR
Sets used alphabet, X can be an ID or a 'list' command,
which will print IDs of all available alphabets.
By default 64\-character alphabet is used.

.TP +19m
\fBcodelength\-\fInum\fR
Set passcode length to \fInum\fR characters,
where \fInum\fR may be between 2 and 16.
(Default: \fBcodelength\-4\fR)

.TP +19m
\fBno\-salt\fR
Meaningful only during key generation. Disables salting of a passcode counter.
Enabling this option will make program compatible with PPPv3.1 and will increase
available passcard number at the cost of (theoretically) less security.
.TP +19m

\fBsalt\fR
Enables salting of key if not enabled by default.


.TP +19m
\fBlist\fR
Display current user state information.
.PD
.RE
.RE

.TP
\fB\-p\fR, \fB\-\-password\fR \fIpassword\fR
Set static password.
Use empty line to unset.

.TP
\fB\-c\fR, \fB\-\-contact\fR \fIstring\fR
Set contact information to \fIstring\fR, to use when passcodes are
sent via an out-of-band channel.
The exact interpretation of \fIstring\fR will depend on the user configuration,
but may be a phone number, IM username, or email address.
Use a empty string ("") to unset this value.

.TP
\fB\-d\fR, \fB\-\-label\fR \fItitle\fR
Set a title for the generated passcards.
This will be displayed at the top of every passcard.
If unset (null), the current hostname will be used by default.

.PD 0
.TP
\fB\-u\fR, \fB\-\-user\fR \fIusername\fR
.TP
\fB\-u\fR, \fB\-\-user\fR \fIUID\fR
Specify the user account upon which to operate.
Normal users may only change their own account, while the superuser may
change any account with this option.
Either a symbolic \fIusername\fR or a numeric \fIUID\fR may be specified.
(Administrator only)
.PD

.SS General
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Display more information about program operation.

.TP
\fB\-\-version\fR
Display license, warranty, version and author information.

.TP
\fB\-h\fR, \fB\-\-help\fR
Program usage and option help information.

.TP
\fB\-\-check\fR
Run \fBotpasswd\fR internal self-test.

.SS Parameter References
When an option accepts a passcode reference (\fIcode\fR),
it can be specified in any of the following ways:
.PD 0
.RS +4m
.TP +10m
#
Passcode number.
Each passcode has a unique decimal number,
starting with the first passcode generated.
.TP +10m
CRR\fB[\fR#\fB]\fR
Passcode address.
Each passcode has a unique address comprised of the
column \fIC\fR (a letter) and row \fIRR\fR (one or more digits) on a
specific passcard number (\fI#\fR).
For example, 'F3[45]' refers to the passcode at column \fIF\fR
and row \fI3\fR of passcard \fI45\fR.
.TP +10m
\fBcurrent\fR
The passcode which will be used for the next authentication.
.RE
.PD

Passcard references (\fIcard\fR) may be specified as follows:
.PD 0
.RS +4m
.TP +10m
\fB[\fR#\fB]\fR
Passcard number.
.TP +10m
\fB[current]\fR
The passcard containing the current passcode.
.TP +10m
\fBnext\fR
The first unprinted passcard.
.RE
.PD

.SH SECURITY NOTES
This section needs to be completed (FIXME). Until this section is written
see docs/security file which is distributed with OTPasswd sources.

.SH EXIT STATUS
This section needs to be completed (FIXME).
OTPasswd will return 0 on success and non-zero 
on failure. This can be used for scripting (e.g. see -a option).

.\"   RETURN VALUE       [Normally only in Sections 2, 3]
.\"   ERRORS             [Typically only in Sections 2, 3]
.\"   ENVIRONMENT

.SH FILES
.TP
/etc/otpasswd
The directory for \fBOTPasswd\fR configuration files.
If \fBOTPasswd\fR is configured to use a global flat-file
database, then this file resides here, also.
The directory should be owned by the special \fIotpasswd\fR
system user,
and should not be accessible for normal users (mode 0700).

.TP
/etc/otpasswd/otpasswd.conf
The main \fBOTPasswd\fR system configuration file.
This file contains key-value configuration parameters that
govern the operation of the system.

This file contains state DB configuration, system-wide defaults,
PAM configuration and policy configuration.

When the backend user database is configured to use MySQL or LDAP,
this file will contain privileged information and
must be not be accessible for normal users.

.TP
/etc/otpasswd/otshadow
The system-wide user database, used only when the \fBotpasswd.conf\fR
specifies the use of a global database backend.
The file contains state information for all users,
including keys, flags, etc, and must not be accessible
to normal users.

.TP
$HOME/.otpasswd
This file is only used when the system configuration file
\fBotpasswd.conf\fR specifies that state information is
to be maintained in user home directories.
This has the same format as \fBotshadow\fR above, except
only contains information for a single user.

.TP
/etc/pam.d/otpasswd_login
The PAM prototype configuration for \fBOTPasswd\fR.
If this file is \fIinclude\fRd in a PAM configuration of any
service (like SSH), the \fBpam_otpasswd\fR(8) PAM module will be 
used to ask the user for a passcode just after normal pam_unix 
authentication mechanisms succeeds.

.TP
/lib/security/pam_otpasswd.so
The \fBOTPasswd\fR system PAM module.
This module is dynamically loaded by \fBPAM\fR(7) when an \fBOTPasswd\fR
one-time password authentication has been configured.
Various runtime options exist for this module to modify
operation.  For more information, see \fBpam_otpasswd\fR(8).

.\"   VERSIONS           [Normally only in Sections 2, 3]

.SH COMPATIBILITY
The \fBOTPasswd\fR authentication system is compatible with the
"Perfect Paper Passwords" specification version 3 (PPPv3) as
developed by the Gibson Research Corporation.
An excellent description of PPPv3 is available on the web at:
<https://www.grc.com/ppp.htm>.
.PP
Note that for \fBOTPasswd\fR to operate in a manner which is
strictly compatible with PPPv3, it is important to specify
the \fB\-f no\-salt\fR option during key generation.
A compatible key will generate passcards, and passcodes
which are interoperable with other PPPv3-compliant applications.
For a list of such applications, see
<http://www.grc.com/ppp/software.htm>.
.PP
\fBOTPasswd\fR does \fInot\fR support any earlier versions
of the PPP specification.

.\"   CONFORMING TO
.\"   NOTES
.\"   BUGS

.SH EXAMPLES
Every user must generate a key in order to use \fBOTPasswd\fR.
A cryptographic salt is used by default, unless the \fB\-f no-salt\fR
option is specified or SALT_DEF parameter in config file changed.
This type of key is not compatible with the PPPv3 specification.
To generate a new salted key and print the first passcard, use:
.PP
.ti +4m
$ otpasswd \-\-flag salt \-\-key
.PP
Typically, to use the \fBOTPasswd\fR authentication system,
a user will carry a series of passcards to consult during system login.
Specific passcards may be printed in either LaTeX or plain ASCII text.
The \fB[\fR character may be a shell metacharacter,
so it may need to be quoted or backslash-escaped.
To print the third passcard in ASCII text, use:
.PP
.ti +4m
$ otpasswd \-\-text '[3]'
.PP
And the current passcard may be printed with:
.PP
.ti +4m
$ otpasswd \-\-text '[current]'
.PP
To configure a passcode length of five (5) characters, use:
.PP
.ti +4m
$ otpasswd \-\-flag codelength\-5
.PP
You can use this option at any time, including key creation.
.PP
While plain ASCII passcards are perfectly useful,
LaTeX enables much more attractively formatted passcards and easy
approach to printing few passcards at a time.
One way to efficiently print a LaTeX file is to use the \fIpdflatex\fR
utility from the \fItexlive-latex-base\fR package.
To generate the next six (6) passcards on an A4 page using LaTeX, use:
.PP
.RS +4m
$ otpasswd \fB\-\-latex\fR next > tmp.latex
.br
$ pdflatex tmp.latex
.br
$ lp tmp.pdf
.br
# Remember to remove any temporary files to keep your passcards secret.
.RE

.SH SEE ALSO
\fBpam_otpasswd\fR(8),
\fBotpasswd.conf\fR(5), 
\fBotshadow\fR(5),
\fB.otpasswd\fR(5)

.SH DOCUMENTATION
The documentation for \fBotpasswd\fR is also maintained as a Texinfo manual.
If the \fBinfo\fR and \fBotpasswd\fR programs are properly installed at your
site, the following command should give you access to the manual:
.PP
.ti +4m
$ info otpasswd
.PP
In addition to this manual, various other documents are included with the
source to this package.
Depending upon the \fBOTPasswd\fR package that was installed,
these documents may be available in the /usr/share hierarchy
of your system.

.\"  *AUTHORS

.SH HISTORY
The creation of this program was inspired by the \fBppp-pam\fR project
(http://code.google.com/p/ppp-pam).
The idea is basically the same.
Initially, contributions were made to \fBppp-pam\fR,
however ultimately it was decided to do a complete rewrite.
The two projects share some code, such as locking functions, but nothing more.
It would be reasonable to think of \fBOTPasswd\fR as a fork of \fBppp-pam\fR.

.SH LICENSE
Copyright (c) 2009,2010 Tomasz bla Fortuna
.PP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program in a LICENSE file.

.SH AVAILABILITY
The latest version of the \fBOTPasswd\fR package is available in source form
at the project website
.nh
https://savannah.nongnu.org/projects/otpasswd
.hy 1

.\" End of File
